### ISSUE TITLE
Not available in meteor 1.10.2

### ISSUE THREAD

**Issue by eugle** [CaptainN/npdev-react-loadable#10]
After upgrading to meteor 1.10.2, error report,Tried npdev:react-loadable@1.0.0-beta.1 and npdev:react-loadable@1.0.0-beta.2，Will find errors

![image](https://user-images.githubusercontent.com/24447931/80170574-d93ac300-861a-11ea-9579-fa41146b3c54.png)

![image](https://user-images.githubusercontent.com/24447931/80170648-ff606300-861a-11ea-8a4e-f1d8bb49bcf4.png)

How to reproduce this problem, just create meteor application, add npdev-reacty-loadable, use immediate error reporting

I think this is a big problem, I deliberately tried to create a new project to test, nothing to do, just introduce npdev-reacty-loadable, like this

![image](https://user-images.githubusercontent.com/24447931/80170746-451d2b80-861b-11ea-8383-ce60f195954f.png)

thanks

When we tested the @loadable/component package, we found that there would be an error as well. That would be a problem

This is an error using @loadable/component

![image](https://user-images.githubusercontent.com/24447931/80171145-2f5c3600-861c-11ea-8dbf-b3ef62714de0.png)

![image](https://user-images.githubusercontent.com/24447931/80171154-33885380-861c-11ea-9bd9-c7b680a5c06a.png)

![image](https://user-images.githubusercontent.com/24447931/80171169-38e59e00-861c-11ea-89f1-8cf549f14e64.png)

![image](https://user-images.githubusercontent.com/24447931/80171181-3e42e880-861c-11ea-9772-d1e76ce4debb.png)

![image](https://user-images.githubusercontent.com/24447931/80171190-46028d00-861c-11ea-9796-68ed43050cd9.png)

If so, I'll test the original react-loadable to see if an error occurs，Then, sure enough, mistakes happen

![image](https://user-images.githubusercontent.com/24447931/80171318-a2fe4300-861c-11ea-80d9-5bdec9e7f822.png)

![image](https://user-images.githubusercontent.com/24447931/80171352-c0cba800-861c-11ea-97f0-9805c49242c3.png)

**Comment by CaptainN** [comment]
Sorry about that - this was caused by an oversight on my part. I accidentally included `node_modules` in my last publish (for beta.2) last night, which included a copy of React. That caused the error.

You should not receive this error after updating to beta.3. If you have any trouble, please let me know!

**Comment by eugle** [comment]
When will beta.3 be available, thanks

**Comment by eugle** [comment]
Great! The problem was solved after the update to beta.3. Thank you very much for your timely feedback and thanks for your package
