### ISSUE TITLE
Reload flicker problem

### ISSUE THREAD

**Issue by eugle** [CaptainN/npdev-react-loadable#14]
I have studied for a long time but still cannot solve this problem. This may be the last problem with meteor+ Apollo + SSR that has troubled me. My program may be a little different from the usual one and different templates need to be loaded according to the domain name.

```
const loadableTemplate = {
	meteor: Loadable({
		loader: () => import('/imports/ui/template/meteor/App'),
		loading: () => <div>loading...</div>,
	}),
	apollo: Loadable({
		loader: () => import('/imports/ui/template/apollo/App'),
		loading: () => <div>loading...</div>,
	}),
};

const GET_TEMPLATE = gql`
	query template($host: String!) {
		template(host: $host) {
			data {
				title
				email
				beian
				link
			}
		}
	}
`;

function App({ host }) {
	const { error, data } = useQuery(GET_TEMPLATE, { variables: { host }, skip: !host });

	if (error)
		return (
			<Div c="f9" fs={12} tc p={30}>
				Error! {error.message}
			</Div>
		);

	const template = _.get(data, 'template.data.title');
	const App = loadableTemplate[template || 'meteor'];

	return (
		<Fragment>
			<App />
			<GlobalStyle />
			<Footer host={host} {..._.get(data, 'template.data')} />
		</Fragment>
	);
}

export default App;
```

Loadable, however, eventually sends the template I don't need to the client, as shown in the red box below

![image](https://user-images.githubusercontent.com/24447931/85222619-3ff81500-b3ef-11ea-98ad-1ab528b1a166.png)

This is the cause of the flicker problem, he will put the other template also loaded,

[look at the repositories](https://github.com/eugle/apollo3-meteor10-ssr), (github)

this is all the source code, you can run directly, you will find the error

**Comment by CaptainN** [comment]
This is a strange way to set this all up, and doesn't follow any of the examples I've seen. What are you trying to accomplish?

**Comment by CaptainN** [comment]
My guess is this is happening because the `loadableTemplate[template || 'meteor'];` is using the value of `template` to make the decision, and that is undefined the first time the `useQuery` hook is run - but I"m not super familiar with Apollo. Please check their docs for more. That means both loadables are being requested.

**Comment by CaptainN** [comment]
I'm going to close this, but if you find something more specific than what I mentioned above, please do reach out.
