### ISSUE TITLE
Add npdev-react-loadable-babel ....

### ISSUE THREAD

**Issue by Saeed-Bahrami** [CaptainN/npdev-react-loadable#16]
hi @CaptainN 
The documentation states that the **npdev-react-loadable-babel** package must be installed and added to the babel configuration file.
I have not installed any package named babel yet, do I have to install babel and then create the config file?
Or just create a **babel.config.json** file and add  **npdev-react-loadable-babel** ?

**Comment by CaptainN** [comment]
This is an optional convenience package. It isn't required, it just cuts down on the boilerplate you have to produce, by filling in the meteor function for you. [Read here](https://github.com/CaptainN/npdev-react-loadable#declaring-which-modules-are-being-loaded).
