### ISSUE TITLE
A request in SSR mode

### ISSUE THREAD

**Issue by Saeeed-B** [CaptainN/npdev-react-loadable#17]
My program works properly until I launch ssr.
This means that by changing the URL, a fetch is performed.
And the component is loaded accordingly.
**But**
But when I implement ssr. Only one fetch is performed and all components are loaded in the same fetch

`
{imports: {Ui: {,…}},…}
imports: {Ui: {,…}}
Ui: {,…}
Pages: {Layout: {,…}, Index: {,…}, Auth: {Login: {,…}, Register: {,…}, ResetPasswrod: {,…}}, NoMatch: {,…}}
PanelAdmin: {Layout: {,…}, Index: {,…}, Setting: {,…}}
PanelUser: {Layout: {,…}, Index: {,…}}
Redux: {Actions: {,…}}
node_modules: {react-no-ssr: {,…}, babel-runtime: {core-js: {object: {,…}, symbol: {,…},…}, helpers: {,…}},…}
`

**Comment by CaptainN** [comment]
Please provide a reproduction, or some code. I can't tell what's going on from this.

**Comment by Saeeed-B** [comment]
@CaptainN hi , tank you.

**This is how I called my components :**  

![1](https://user-images.githubusercontent.com/36485982/96410721-368f8580-11f4-11eb-8c6a-a939a9e4f938.png)


Also on my **client side**, I rendered the components like this : 

![2](https://user-images.githubusercontent.com/36485982/96410825-5fb01600-11f4-11eb-9824-e731916e6abe.png)


Also on my **server side**, I rendered the components like this : 

![3](https://user-images.githubusercontent.com/36485982/96410938-8cfcc400-11f4-11eb-95e6-3420363008ac.png)

**Comment by Saeeed-B** [comment]
**When we check we see that it is fetched only once and all the components were called in the same fetch :** 

![4](https://user-images.githubusercontent.com/36485982/96416178-86724a80-11fc-11eb-9af5-7c18fe987481.png)

**Comment by Saeeed-B** [comment]
@CaptainN 
Hellow . are someone here?

**Comment by CaptainN** [comment]
It's fine that only one fetch is performed. Meteor will batch module requests if they are made in the same tick. This is desired behavior.

I'm not sure what isn't working based on your description. Also, your screenshots don't have quiet enough information. If you could create a stripped down project, and put it on github, that would be more helpful.

**Comment by Saeeed-B** [comment]
@CaptainN  I will definitely upload on github.

**But the question is, why when a ssr is not added, with each url change, a fetch is performed.**

**But when ssr is implemented, all components in the main url are loaded with A fetch**

**Comment by CaptainN** [comment]
Is this just a curiosity? It's basically doing a fetch for all modules it doesn't currently have, whenever it needs them. If you are splitting at the route level, then of course it's going to fetch new modules when the routes load - whether that's the first route, or another one, it doesn't matter. If you use [bundle-visualizer](https://docs.meteor.com/packages/bundle-visualizer.html), you'll see that your initial bundle will not have all the modules (or more accurately, you'll see that many of them are "stubbed" - they are too small to contain the actual module code - that's the code splitting in action).

**Comment by Saeeed-B** [comment]
No, not out of curiosity, I just wanted to make sure that my software supports lazy loading properly and that there is no problem with the software getting bigger.

**Comment by eugle** [comment]
same problem

**Comment by CaptainN** [comment]
I'm not sure what you mean, @eugle. I'm going to close this, but feel free to continue the conversation.
