### ISSUE TITLE
Please make the meteor add npdev:react-loadable works

### ISSUE THREAD

**Issue by minhna** [CaptainN/npdev-react-loadable#2]
I tried to install but it failed:
```
meteor add npdev:react-loadable
 => Errors while parsing arguments:           
                                              
While adding package npdev:react-loadable:
error: no such package
```
Thank you.

**Comment by CaptainN** [comment]
I didn't have this published to atmosphere yet, because there are a couple of things left to complete - specifically, porting the tests, and restoring `Loadable.Map`.

I've gone ahead and launched it to atmosphere as an alpha. If you'd like to, give it a go and let me know how it works for you.
