### ISSUE TITLE
Compatibility with renderToNodeStream? 

### ISSUE THREAD

**Issue by treehouseops** [CaptainN/npdev-react-loadable#26]
Thanks for all your work on this! I've been trying to adapt this to work with renderToNodeStream

There are some docs on how to get it to work with the original `react-loadable`: https://loadable-components.com/docs/server-side-rendering/#streaming-rendering 

It seems like `loadableHandle` isn't initialized with the handles and .toScriptTag() until after renderToString is called, is there a way to adapt this so it'll be work with renderToNodeStream?

**Comment by CaptainN** [comment]
"Loadable Components" is a different package, with a different API. If you want to use npdev:react-loadable, you'll need to follow the instructions in the [readme](https://github.com/CaptainN/npdev-react-loadable#readme).

I did get this working ages ago in a starter. Maybe that'll [help as a reference](https://github.com/CaptainN/meteor-react-starter/blob/master/server/main.js). I'll also say, that it's not necessarily easy to set up...

If you have any questions, I'm happy to try to answer them.

**Comment by treehouseops** [comment]
That helps a lot. Seem like it's not worth the probably minor performance bump. 

And yes, I did get it working with the readme no problem, very clear! I was only using the "loadable components" docs as a reference to see if there were any hints of how to structure it!
