### ISSUE TITLE
Check LoadableMap's SSR support

### ISSUE THREAD

**Issue by CaptainN** [CaptainN/npdev-react-loadable#3]
One of the things I did in porting this initially was to simplify the preloadable data format (from a multi-dimensional array to a flat array). I'm not sure what implications this will have for LoadableMap.

**Comment by eugle** [comment]
Found a problem with loadableMap, all files in the loader will be rendered by the client,

```
const Apps = LoadableMap({
	loader: {
		meteor: () => import('/imports/ui/template/meteor/App'),
		apollo: () => import('/imports/ui/template/apollo/App'),
		abc: () => import('/imports/ui/template/abc/App'),
	},
	loading: () => <div>loading...</div>,
	render(loaded, props) {
		console.log(loaded);
		console.log(props);
		let Meteor = loaded.meteor.default;
		return <Meteor {...props} />;
	},
});
```


```
return (
		<Fragment>
			<Apps {...props} />
			<GlobalStyle />
			<Footer host={host} {..._.get(data, 'template.data')} />
		</Fragment>
	);
```

![image](https://user-images.githubusercontent.com/24447931/85221503-cc520a00-b3e6-11ea-9b54-06372d3e040d.png)

Is there any way to solve this problem? I hope you can see that this problem has been bothering me for a long time

**Comment by CaptainN** [comment]
That fetch command is not a render command. Meteor will batch dynamic import requests in 1 request. This is exactly what I would expect to see in the network tab given your code.

**Comment by CaptainN** [comment]
Unless there is a problem created by loading all the modules at once, I don't think there's anything actionable to do here. If I'm wrong, please re-open and let me know.
