### ISSUE TITLE
Where is the full example ? Can I use React 15.6  with it ?

### ISSUE THREAD

**Issue by norain2050** [CaptainN/npdev-react-loadable#6]
1、I hope a full example for SSR to client and server 
2、I must use React 15.6 and React-dom 15.6 ，I want npdev-react-loadable to support 

Can I have these ?

**Comment by minhna** [comment]
It uses react hooks then the minimum version of react must be 16.8

**Comment by CaptainN** [comment]
You can find a full example in [my starter](https://github.com/CaptainN/meteor-react-starter).
