### ISSUE TITLE
Does not support multiple level loadable

### ISSUE THREAD

**Issue by minhna** [CaptainN/npdev-react-loadable#7]
I tried with 2 (or more) levels of loadable. The server render looks fine but the client doesn't work.

**Comment by CaptainN** [comment]
That was tricky to get right - maybe I broke that along the way. I'll get the tests dusted off, and see what's up with it. I'll add a section to my starter that does it this way and play with it.

**Comment by eugle** [comment]
@CaptainN Did you fix the problem

**Comment by CaptainN** [comment]
It's possible, but I honestly don't remember I don't use this feature, and even considered removing it, since I'm not sure when I'll be able to get to fixing it. Besides, meteor batches dynamic import requests - I'm not sure how necessary this is.

**Comment by CaptainN** [comment]
Are you guys still seeing this? I just tested this, and it seems to be working. I'm going to close.

If you are still seeing this, or you have a reproduction (hopefully), please re-open.
