### ISSUE TITLE
Meteor 1.10 or above is not supported

### ISSUE THREAD

**Issue by eugle** [CaptainN/npdev-react-loadable#9]
Report an error after deployment,

![image](https://user-images.githubusercontent.com/24447931/78451603-0a2d7500-76b9-11ea-8846-be162b579b97.png)

Reproduce the error,Just need to upgrade meteor to 1.10.1

**Comment by eugle** [comment]
On the server side, it's different from loadable.capture

This is the react - loadable: 
![image](https://user-images.githubusercontent.com/24447931/78422698-c5dbae00-7693-11ea-82d5-4924b5f699a9.png)

This is you:
![image](https://user-images.githubusercontent.com/24447931/78422711-d855e780-7693-11ea-8f49-36b15b599fb6.png)

**Comment by CaptainN** [comment]
This is working fine for me with Meteor 1.10.1. Can you post some code so I can determine if this is something in the package code or in your implementation? Thanks in advance!

**Comment by eugle** [comment]
This should be my problem, please close this problem, sorry

**Comment by CaptainN** [comment]
I'm glad you got it working. If there is some way I could improve the documentation or make this easier to set up, please let me know!
